### ISSUE TITLE
Unable to scale animated luasprites using functions 

### ISSUE THREAD

**Issue by Zexlo** [Zexlo/FNF-Sonic-EXE-psych-engine-port#12]
I can't make choas' stage if I can't scale down the front layer anim sprite

**Comment by CarpetBook** [comment]
Found that Porker was assigned the key 'anim' when Lua sprite was made, then 'anim' was not scaled in the scaleObject.
- Renamed key 'anim' to 'porker' and corrected scale and position. Set scroll factor of Porker to 1.2 for foreground parallax.
- Added Fleetway Super Sonic character files and assigned animations. 
Fleetway Super Sonic now works, but fleetway1/2/3 need better offsets, and chart needs new animations added. Still no other stage elements added yet. Committing to supersonic branch.

**Comment by Zexlo** [comment]
how do i use this camera? do i load the stage in freeplay? also thanks!

**Comment by CarpetBook** [comment]
In the "supersonic" branch the camera is enabled by default for *every* song. It's in the "scripts" folder in the mod, so it'll run on every song, every difficulty at the moment. It's just for debugging and checking stage object positions, since there's no easy way to see everything at once...

**Comment by Zexlo** [comment]
the stage editor/creator is planned LAST for psych engine so its a shame we'll never get to take advantage of it during the mods development

**Comment by CarpetBook** [comment]
Massively revamped free camera script; disabled by default for all songs in the mod. Press 1 to enable the free camera in a song. Press I, J, K, and L to move the camera. Hold Shift to move the camera faster. Press 1 again to disable the free camera and return the camera to the game. Press 2 to keep the camera in place while disabling camera controls.

In stage script: Reset some scroll factors for `CWall`, `CFloor`, and `pebles` so that the stage objects follow the environment correctly; now they no longer slide across the floor as the camera pans.

In Chaos song script: precached Porker's image on creation. Needs to be verified to work on other computers, but this seemed to reduce the lag spike to just a few frames of lag on my computer. Reopening issue until this fix is verified to work elsewhere.
